# Generated by Django 5.1.2 on 2024-10-13 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('google_access_token', models.CharField(blank=True, max_length=100, null=True)),
                ('google_refresh_token', models.CharField(blank=True, max_length=100, null=True)),
                ('google_token_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('google_scopes', models.CharField(blank=True, max_length=255, null=True)),
                ('google_enabled', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
