# Generated by Django 5.1.3 on 2024-11-17 10:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveCohort',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('max_students', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts_taught', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LiveCohortRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.livecohort')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='livecohort',
            name='students',
            field=models.ManyToManyField(through='classes.LiveCohortRegistration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SelfPacedClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_paced_classes_taught', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SelfPacedClassRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
                ('sp_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.selfpacedclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='selfpacedclass',
            name='students',
            field=models.ManyToManyField(through='classes.SelfPacedClassRegistration', to=settings.AUTH_USER_MODEL),
        ),
    ]
