# Generated by Django 5.1.4 on 2024-12-22 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_remove_livecohort_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfPacedLesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('lesson_number', models.PositiveSmallIntegerField(default=1)),
                ('content', models.TextField(blank=True, null=True)),
                ('sp_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='classes.selfpacedclass')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SelfPacedClassUpload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='self_paced/uploads')),
                ('sp_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='classes.selfpacedclass')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='classes.selfpacedlesson')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SelfPacedLessonHomework',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='classes.selfpacedlesson')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
