# Generated by Django 5.1.5 on 2025-01-24 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_selfpacedlesson_selfpacedclassupload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfpacedclass',
            name='students',
        ),
        migrations.RemoveField(
            model_name='selfpacedclass',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='selfpacedlesson',
            name='sp_class',
        ),
        migrations.RemoveField(
            model_name='selfpacedclassregistration',
            name='sp_class',
        ),
        migrations.RemoveField(
            model_name='selfpacedclassupload',
            name='sp_class',
        ),
        migrations.RemoveField(
            model_name='selfpacedclassregistration',
            name='student',
        ),
        migrations.RemoveField(
            model_name='selfpacedclassupload',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='selfpacedlessonhomework',
            name='lesson',
        ),
        migrations.DeleteModel(
            name='PrivatePackage',
        ),
        migrations.DeleteModel(
            name='SelfPacedClass',
        ),
        migrations.DeleteModel(
            name='SelfPacedClassRegistration',
        ),
        migrations.DeleteModel(
            name='SelfPacedClassUpload',
        ),
        migrations.DeleteModel(
            name='SelfPacedLesson',
        ),
        migrations.DeleteModel(
            name='SelfPacedLessonHomework',
        ),
    ]
