# Generated by Django 5.1.5 on 2025-01-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_livecohort_end_date_livecohort_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livecohortassignment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
        migrations.AddField(
            model_name='livecohortassignment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livecohortassignment',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livecohortassignmentsubmission',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livecohortassignmentsubmission',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
    ]
