# Generated by Django 5.1.5 on 2025-01-27 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0006_livecohortassignment_attachment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livecohortassignment",
            name="cohort",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="classes.livecohort",
            ),
        ),
    ]
