# Generated by Django 5.1.5 on 2025-01-28 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0007_alter_livecohortassignment_cohort"),
        ("quizzes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveCohortQuiz",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("due_date", models.DateTimeField()),
                ("is_required", models.BooleanField(default=True)),
                ("points", models.PositiveIntegerField(default=0)),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohort_quizzes",
                        to="classes.livecohort",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quizzes.quiz"
                    ),
                ),
            ],
            options={
                "unique_together": {("cohort", "quiz")},
            },
        ),
        migrations.AddField(
            model_name="livecohort",
            name="quizzes",
            field=models.ManyToManyField(
                through="classes.LiveCohortQuiz", to="quizzes.quiz"
            ),
        ),
    ]
