# Generated by Django 5.1.5 on 2025-02-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_alter_livecohortassignment_cohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='livecohortassignment',
            name='submission_optional',
            field=models.BooleanField(default=False),
        ),
    ]
