# Generated by Django 5.1.5 on 2025-03-23 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0008_livecohortsession_video_recording_link_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveCohortWaitList",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("questions", models.TextField(blank=True, null=True)),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to="classes.livecohort",
                    ),
                ),
            ],
            options={
                "unique_together": {("cohort", "email")},
            },
        ),
    ]
