# Generated by Django 5.1.5 on 2025-02-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_livecohortassignment_submission_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='livecohort',
            name='course_fees',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livecohort',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livecohort',
            name='key_topics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livecohort',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livecohort',
            name='schedule',
            field=models.TextField(blank=True, null=True),
        ),
    ]
