# Generated by Django 5.2.5 on 2025-08-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_livecohortwaitlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='livecohort',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
