# Generated by Django 5.2.5 on 2025-08-28 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_livecohort_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='livecohortwaitlist',
            unique_together=set(),
        ),
    ]
