# Generated by Django 5.1.2 on 2024-10-31 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profilecategory",
            options={"ordering": ["order"]},
        ),
        migrations.RenameField(
            model_name="profilecategory",
            old_name="hidden",
            new_name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="bsky_url",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="mastodon_url",
        ),
        migrations.AlterUniqueTogether(
            name="profilecategory",
            unique_together={("profile", "order")},
        ),
        migrations.AddField(
            model_name="profile",
            name="email_url",
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="youtube_url",
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="profilecategory",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profilecategory",
            name="title",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="facebook_url",
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="instagram_url",
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="profile",
            name="threads_url",
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="twitter_url",
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="website_url",
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="profilecategory",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="landing.profile"
            ),
        ),
        migrations.CreateModel(
            name="ProfileLink",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="landing/links/"
                    ),
                ),
                ("url", models.URLField(max_length=512, null=True)),
                ("is_hidden", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("click_count", models.PositiveIntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uncategorized_links",
                        to="landing.profile",
                    ),
                ),
                (
                    "profile_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorized_links",
                        to="landing.profilecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="ProfileCategoryLink",
        ),
        migrations.RemoveField(
            model_name="profilecategory",
            name="name",
        ),
        migrations.AddConstraint(
            model_name="profilelink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("profile_category__isnull", False)),
                fields=("profile_category", "order"),
                name="unique_category_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="profilelink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("profile_category__isnull", True)),
                fields=("profile", "order"),
                name="unique_profile_order_for_uncategorized",
            ),
        ),
    ]
