# Generated by Django 5.1.5 on 2025-01-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizattempt",
            name="attempt_number",
        ),
        migrations.AlterField(
            model_name="quizattempt",
            name="score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
